project:
  type: website
  output-dir: docs

website:
  title: "Kiya Pupa"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - mywork.qmd
      - carbonmarkets.qmd
      - Photography.qmd

format:
  html:
    theme:
      - styles.scss
    css: styles.css
    mainfont: Sans Pro
    toc: true
    page-layout: full

editor: visual

