project:
  type: "Kiya Pupa"
  output-dir: docs

website:
  title: "kiyapupa.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - mywork.qmd

format:
  html:
    theme: quartz
    css: styles.css
    toc: true
    page-layout: full

editor: visual

